#!/bin/bash

build() {

    add_module "cdrom"
    add_module "loop"
    add_module "dm-snapshot"
    add_module "overlay"
    add_module "isofs"
    add_module "squashfs"
    add_module "hfsplus"
    add_module "sr_mod"
    add_module "dm_mod"
    add_module "dm-raid"
    add_module "raid0"
    add_module "raid1"
    add_module "raid10"
    add_module "raid456"

    add_runscript

    add_all_modules -f 'nls' '/kernel/fs'
    add_all_modules -f 'overlayfs' '/kernel/fs'
    add_all_modules -f 'squashfs' '/kernel/fs'
    add_all_modules -f 'udf' '/kernel/fs'
    add_all_modules -f 'ext4' '/kernel/fs'
    add_all_modules -f 'hfsplus' '/kernel/fs'
    add_all_modules -f 'btrfs' '/kernel/fs'
    add_all_modules -f 'usb-storage' '/kernel/drivers/usb'
    add_all_modules -f 'mmc_block' '/kernel/drivers/mmc'
    add_all_modules -f 'nvme' '/kernel/drivers/nvme'
    add_all_modules -f 'virtio' '/kernel/drivers/virtio'
    
    add_binary "timeout"
    add_binary /usr/lib/udev/cdrom_id
    add_binary blockdev
    add_binary dmsetup
    add_binary losetup
    add_binary truncate
    add_binary gpg
    add_binary grep
    
    add_file /usr/lib/udev/rules.d/60-cdrom_id.rules
    add_file /usr/lib/udev/rules.d/10-dm.rules
    add_file /usr/lib/udev/rules.d/95-dm-notify.rules
    add_file /usr/lib/initcpio/udev/11-dm-initramfs.rules /usr/lib/udev/rules.d/11-dm-initramfs.rules
}

help() {
    cat << HELPEOF
Adds needed modules to the initramfs image.
HELPEOF
}
